spring:
  datasource:
    url:  jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false
    #jdbc:mariadb://localhost:3306/test
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:${GCS_KEY}.json
    project-id: ${GCS_PROJECT_ID}
    bucket: ${GCS_BUCKET_NAME}

openai:
  key: ${GPT_KEY}
  dns: ${GPT_URL}
  model: ${GPT_MODEL}